### ISSUE TITLE
Android App Crashes after install plugin 

### ISSUE THREAD

**Issue by andirsun** [rlfrahm/capacitor-apple-login#1]
Hi,after install the plugin ios app runs fine but android crash with this log
`2020-05-03 19:30:06.424 6438-6438/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.timugo.pets, PID: 6438
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.timugo.pets/com.timugo.pets.MainActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.CoordinatorLayout" on path: DexPathList[[zip file "/data/app/com.timugo.pets-1/base.apk"],nativeLibraryDirectories=[/data/app/com.timugo.pets-1/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:609)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:56)
        at com.timugo.pets.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
`

**Comment by andirsun** [comment]
@rlfrahm any solution ?

**Comment by rlfrahm** [comment]
Hi @andirsun, Android does not work with this plugin currently.

**Comment by YogiBear52** [comment]
Is there any workaround to get it work? 
It works great for IOS but now my Android project is broken.

Every capacitor sync/update command adds a reference to this plugin what makes the build fail. When trying to remove the gradle references it fails on runtime.
I am using capacitor 2.1

Maybe a way to ignore this plugin when compiling to Android? 
@rlfrahm 

Thanks

**Comment by andirsun** [comment]
> Is there any workaround to get it work?
> It works great for IOS but now my Android project is broken.
> 
> Every capacitor sync/update command adds a reference to this plugin what makes the build fail. When trying to remove the gradle references it fails on runtime.
> I am using capacitor 2.1
> 
> Maybe a way to ignore this plugin when compiling to Android?
> @rlfrahm
> 
> Thanks

The unique way to fix is every time you make "capacitor update", go and coment the importation of the plugin in android.

**Comment by YogiBear52** [comment]
> > Is there any workaround to get it work?
> > It works great for IOS but now my Android project is broken.
> > Every capacitor sync/update command adds a reference to this plugin what makes the build fail. When trying to remove the gradle references it fails on runtime.
> > I am using capacitor 2.1
> > Maybe a way to ignore this plugin when compiling to Android?
> > @rlfrahm
> > Thanks
> 
> The unique way to fix is every time you make "capacitor update", go and coment the importation of the plugin in android.

Thanks, I hope it will be fixed because it is super annoying.

**Comment by andirsun** [comment]
> > > Is there any workaround to get it work?
> > > It works great for IOS but now my Android project is broken.
> > > Every capacitor sync/update command adds a reference to this plugin what makes the build fail. When trying to remove the gradle references it fails on runtime.
> > > I am using capacitor 2.1
> > > Maybe a way to ignore this plugin when compiling to Android?
> > > @rlfrahm
> > > Thanks
> > 
> > 
> > The unique way to fix is every time you make "capacitor update", go and coment the importation of the plugin in android.
> 
> Thanks, I hope it will be fixed because it is super annoying.
Yes, I think that the guy who made the plugin its a "APPLE guy" and dont cares the android projects. In our startup we are currently working in a cross platform apple plugin, works in android, pwa, ios.

**Comment by andirsun** [comment]
> > > Is there any workaround to get it work?
> > > It works great for IOS but now my Android project is broken.
> > > Every capacitor sync/update command adds a reference to this plugin what makes the build fail. When trying to remove the gradle references it fails on runtime.
> > > I am using capacitor 2.1
> > > Maybe a way to ignore this plugin when compiling to Android?
> > > @rlfrahm
> > > Thanks
> > 
> > 
> > The unique way to fix is every time you make "capacitor update", go and coment the importation of the plugin in android.
> 
> Thanks, I hope it will be fixed because it is super annoying.

Np bro, in our startup we are working in a capacitor apple crossplatform plugin.

**Comment by rlfrahm** [comment]
I've not worked on capacitor recently so I'm not sure what the fix needs to be. Pull requests are very much welcome.

**Comment by rickbeumers** [comment]
Wouldn't this problem be fixed by just removing the Android folder from the root of the plugin? That way it shouldn't add any code the the Android project and by that not breaking it.
